---
- hosts: all
  sudo: True
  tasks:
    - name: add cassandra debian repository
      apt_repository: repo='deb http://www.apache.org/dist/cassandra/debian 20x main'

    - name: add the key for the cassandra debian repo
      apt_key: keyserver=pgp.mit.edu id=F758CE318D77295D

    - name: add the other key for cassandra
      apt_key: keyserver=pgp.mit.edu id=2B5C1B00

    - name: install cassandra
      apt: name=cassandra update_cache=yes
